In [1]:
from PandOpt import pandopt
import pandas as pd
import numpy as np
import tqdm 
import pandas as pd
import numpy as np
import timeit
import functools


In [2]:
# Example usage
def simple_start(z):
    x = (z['A'] + z['B']) / z['C']
    x += z['B'] * z['D']
    return x / z['B']

def harder_func(z):
    x = (z['A'] + z['B']) / z['C']
    if x > 0:
        return x / z['B']
    x += z['B'] * z['D']
    return x * z['B']

def harder2_func(z):
    x = (z['A'] + z['B']) / z['C']
    if (k:=z['A']-z['C']) > (j:=z['B']/z['D']):
        return x / k
    x *= j
    return x - k if k > z['C'] else x + k

def harder3_func(z):
    g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
    x = (z['A'] + z['B']) / z['C']
    if (k:=z['A']-z['C']) > (j:=g(z['B'],z['D'])):
        return j / k
    x *= j
    return x - k if k > z['C'] else x + k
        

In [3]:

def measure_performance(df, func, test_type, window_size=3):
    try:
        if test_type == "apply":
            operation = functools.partial(df.apply, func, axis=1)
        elif test_type == "rolling":
            operation = functools.partial(df.rolling(window=window_size).apply, func, raw=True)
        elif test_type == "groupby":
            operation = functools.partial(df.groupby('A').apply, func)
        else:
            raise ValueError("Invalid test type")

        start_time = timeit.default_timer()
        result = operation()
        elapsed_time = timeit.default_timer() - start_time
        return np.sum(result, axis=0), elapsed_time, None
    except Exception as e:
        return None, None, str(e)

def run_tests(data_size, test_funcs, agg_funcs, test_types):
    results = {}
    total_tests = (data_size - 1) * len(test_funcs + agg_funcs) * len(test_types)
    progress_bar = tqdm.tqdm(total=total_tests, desc="Running Tests", ncols=100)

    for test_num in range(1, data_size):
        df_size = int(10**test_num)
        for func in test_funcs + agg_funcs:
            for test_type in test_types:
                for test_iter in range(15):
                    pandas_df = pd.DataFrame(np.random.randn(df_size, 4), columns=['A', 'B', 'C', 'D']).astype(np.float32)
                    pandopt_df = pandopt(pandas_df)
                    pandas_checksum, pandas_time, pandas_error = measure_performance(pandas_df, func, test_type)
                    pandopt_checksum, pandopt_time, pandopt_error = measure_performance(pandopt_df, func, test_type)
    
                    key = f"Size: 10^{test_num}, Func: {func.__name__}, Test: {test_type} - {test_iter}"
                    results[key] = {
                        "Pandas Time (s)": pandas_time,
                        "Pandopt Time (s)": pandopt_time,
                        "Checksum Pandas": pandas_checksum,
                        "Checksum Pandopt": pandopt_checksum,
                        "Pandas Error": pandas_error,
                        "Pandopt Error": pandopt_error
                    }
    
                progress_bar.update(1)

    progress_bar.close()
    return pd.DataFrame.from_dict(results, orient='index')

# Run the tests
test_functions = [simple_start, harder_func, harder2_func, harder3_func]
agg_functions = []
test_types = ["apply"]

results_df = run_tests(data_size=7, test_funcs=test_functions, agg_funcs=agg_functions, test_types=test_types)
results_df

Running Tests:   0%|                                                         | 0/24 [00:00<?, ?it/s]

{} <function simple_start at 0x7f3f10e8da80>


Running Tests:   4%|██                                               | 1/24 [00:02<00:54,  2.38s/it]

[[ 1.1913959  -1.4160854  -0.49710423 -0.79077286 -0.21559821 -0.56292164
   0.35779637  0.14562789  0.04355303 -0.6078642 ]
 [-0.32915676 -0.19780855 -0.51590395  1.1348498   1.091438   -0.03214883
  -1.3134284  -0.01052305  1.3225116  -0.20755357]
 [ 0.8724099   1.5013642  -0.19882569  1.218727   -0.02052601 -0.07454454
  -0.46017504 -1.1258476  -2.478252    1.1302408 ]
 [ 1.3774569  -1.314558    1.4085132   0.57591784 -1.7834837  -0.74544495
   1.5888186   0.46047986 -0.84852886 -0.01667917]]
[-1.1099603 -4.028935  -6.7333546  0.5419473]
{} <function simple_start at 0x7f3f10e8da80>
[[ 0.52196586 -0.05863949 -0.66604275  3.0551147  -1.1634499  -0.17275524
   2.0706675  -1.0757242  -0.13815308 -1.2094935 ]
 [ 1.5110989  -0.5796262  -0.07275017  0.23985982  1.839315   -0.78656507
  -1.0679615  -0.47034198 -0.4728131   2.271437  ]
 [-1.5979162  -0.08871783  0.624515   -0.72790307 -0.48351052  1.0311408
   1.4403129  -2.266021   -1.5474056   0.43351176]
 [ 1.0136257   0.62720704  0.43180

Running Tests:   8%|████                                             | 2/24 [00:04<00:55,  2.51s/it]

[[-0.9272081  -0.17881027  0.6525728  -0.4720727   0.3876871  -0.7964478
  -2.081776    0.27959138 -1.053731   -1.0313725 ]
 [ 0.17352462 -0.57077265  0.02718984 -0.7267992   1.9938073  -0.14101903
  -0.8157961   0.4822403   0.44957134  1.6771429 ]
 [-0.07962336 -1.3395982  -1.3908387  -0.57712525 -0.342953    0.6844035
  -0.9892442   0.4592548   1.0947556   0.30363536]
 [-0.73973304  0.0710858  -0.48262215 -0.19891754 -0.43617004  1.1038916
  -1.5587486  -0.9015623  -0.7821209   1.287841  ]]
[[ 0.28796443]
 [ 8.10230637]
 [-0.76172614]
 [19.48978233]]
{} <function harder_func at 0x7f3f10e8db20>
[[ 1.0936815   0.49037883  0.7448064   0.10551041  1.3231411   1.9093816
  -0.3882217  -0.11415902 -1.5552276  -0.6976019 ]
 [-0.08847206 -0.41829482 -3.0658128   1.5182345   0.8142461   1.069994
  -0.47617507  0.0646446   1.3470023   1.5002414 ]
 [-1.0018343   1.7800038   0.2748413   0.7393166  -0.63113725 -0.72347873
  -0.5639265   0.8391963  -0.10138126  0.25354502]
 [ 0.23486279 -2.106751  

Running Tests:  12%|██████▏                                          | 3/24 [00:05<00:30,  1.46s/it]/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) el

{} <function harder3_func at 0x7f3f10e8dda0>
[[ 0.10788345  0.6878886  -0.93319803 -1.7014674   0.9090192   0.78729576
   2.0766459  -0.77681047 -0.9505328  -1.1290791 ]
 [ 0.15349099  0.66028     1.4643308  -0.08080846 -0.39563194 -0.37830022
   0.89207655  1.4585878  -1.0708284   1.0998529 ]
 [ 0.26426777 -0.28153014 -0.14614384  0.64399153 -0.9971615   0.23352961
   0.21903488 -2.3777943   0.50160193  1.5689222 ]
 [-0.20883109  1.3009552   1.2433685   0.8840448  -1.8420984   0.41831678
   1.0789636   0.18563321  0.6403719   0.736179  ]]
[[        nan]
 [-0.94390309]
 [-4.30530949]
 [-0.30949366]]
{} <function harder3_func at 0x7f3f10e8dda0>
[[ 0.5349898  -1.6018465   1.7542588  -0.02398206  0.40056023  0.65516984
   1.456426    0.63693047 -1.780064    1.7874608 ]
 [-0.8490135   0.40918958  0.2424734  -0.9435515  -0.15391356 -0.18316346
  -0.4872541   0.7289003   0.90530556  1.0880952 ]
 [ 0.6988343   0.9296312  -1.3959862   0.78407127  0.18153612  2.577392
  -0.07179128 -0.02466834 

Running Tests:  29%|██████████████▎                                  | 7/24 [00:05<00:06,  2.64it/s]

{} <function harder_func at 0x7f3f10e8db20>
[[-0.45775497  1.5771829   0.6095552  -0.6129299   1.513146   -0.17824638
  -0.9605135   0.2021738  -0.32043698  0.76679844  0.94889104  0.43340984
  -0.17914619  1.4158211   2.2080007  -0.7841926   2.3104458   1.023561
  -0.39366466 -1.057987   -0.1051369   1.3286303  -1.2290335  -2.459597
  -0.7626125  -0.77457243 -1.0140324  -0.5866859   0.70653856 -2.819121
   1.2821335   0.43081295  1.2954351  -0.4926924  -1.4048645   0.11267194
   1.3832672  -0.70197475  1.6292179  -0.91959226 -0.08151137 -0.88938755
  -1.3055503  -2.0014384  -1.0900472  -2.7974508   0.69002086 -0.96334326
   1.4396073   1.1836181   0.47563666 -0.28026044 -0.20461336  0.42473218
  -0.6546101  -0.40566558 -0.00669473  0.8210222   0.2543849   0.39972156
   0.6222072   0.08390258  0.24661832 -0.6837871   1.1808659  -0.12110398
   0.33925647 -0.83376557  1.2253151   0.8505452  -0.71009576 -1.7490392
   0.7517994   0.08914378  0.95218796  0.11427752 -0.8025017  -0.12028998
 

/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel

[[-0.7602981  -1.712763    1.9519116  ... -0.4994658  -1.3523953
  -0.61409223]
 [-0.21962808 -0.68438435  1.1057975  ...  0.00809996 -1.612917
  -1.6390152 ]
 [ 1.4140465  -0.36019325 -0.39493904 ... -1.9526992   0.8557316
   0.35481483]
 [-1.3833894   0.03298469  0.33359507 ... -2.7749562   0.35271767
   0.8638611 ]]
[  -1.4780211    0.8451457    8.208929  -122.41353  ]
{} <function simple_start at 0x7f3f10e8da80>
[[ 0.4459256   1.246501    0.1761382  ... -1.0163102   2.3368473
  -0.68701464]
 [-1.2395102  -0.24459042  0.6611289  ... -0.43106282 -0.30841002
   1.0308565 ]
 [ 1.5644603   0.19311103  1.4750023  ... -0.42310974 -0.768035
  -0.6067481 ]
 [ 0.47910428  0.18563777 -0.5556027  ... -0.58040625 -0.713083
   0.24242912]]
[ 7.6821327  9.457831   6.107366  -5.953674 ]
{} <function simple_start at 0x7f3f10e8da80>
[[-1.164601   -1.3423356  -0.22781396 ... -0.12006908  0.6309767
   0.06412075]
 [ 0.8803473  -0.8185338  -1.2859696  ... -0.9127248  -0.24837364
  -3.244232  ]
 [-0.319

Running Tests:  46%|██████████████████████                          | 11/24 [00:06<00:03,  4.20it/s]/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value e

{} <function harder3_func at 0x7f3f10e8dda0>
[[-0.5855702  -0.5244076   0.13308491 ...  0.4098126   0.18826056
  -2.2266204 ]
 [-0.5651989  -1.189814   -0.41401988 ... -0.79599875 -0.18887697
   0.07078653]
 [-1.2148896  -1.4377624   0.02389848 ...  1.6420345  -0.3111609
  -1.215007  ]
 [-0.31929934  0.03014944 -1.0360615  ... -0.8827105   1.4287938
   0.10791106]]
[[        nan]
 [ 7.87023211]
 [ 1.16062009]
 [-2.862228  ]]
{} <function harder3_func at 0x7f3f10e8dda0>
[[ 1.1922082  -1.0701194  -0.03671108 ... -1.773939   -0.9949627
  -1.7629136 ]
 [ 1.8639234   1.2212971  -0.2914136  ...  1.3500624   2.7157238
  -0.00342338]
 [ 0.64330876  0.40170026  0.85083795 ...  0.5516354  -0.46384573
  -1.280964  ]
 [-0.3264717  -0.7334002   2.0125444  ...  2.0731497  -1.028485
   0.3823138 ]]
[[        nan]
 [        nan]
 [ 0.2858437 ]
 [-1.28275932]]
{} <function harder3_func at 0x7f3f10e8dda0>
[[-1.2630799  -0.3214849   0.3716404  ... -0.8749346  -0.741891
  -1.9687223 ]
 [ 0.69038016  0.627

Running Tests:  54%|██████████████████████████                      | 13/24 [00:07<00:05,  2.01it/s]

{} <function simple_start at 0x7f3f10e8da80>
[[ 0.03576034  0.47967038 -0.8808058  ... -0.659652    1.1643907
  -1.5210911 ]
 [-0.07941372 -1.4642179  -0.15547155 ...  2.1973662  -0.8848046
  -0.11578151]
 [-0.08815663  0.02332699  0.27781937 ... -0.44180706 -0.18758546
   0.08928698]
 [-2.1874285   0.04852685  0.67852396 ... -1.0910673  -0.7792166
  -0.48864427]]
[ -1.2265613  -7.2448864 -10.397941  -65.833885 ]
{} <function simple_start at 0x7f3f10e8da80>
[[ 1.3946412   0.11673877  0.39782438 ... -0.89188266  0.19366013
   1.3345256 ]
 [-0.6323595  -0.7995915  -0.25707656 ...  0.9067798  -0.12862842
  -0.47667792]
 [-1.0089264  -0.25723305  0.9979076  ...  0.11598367  1.0425419
   0.34559664]
 [ 0.6671505   0.07933658  0.4245046  ...  0.47354978 -1.7730666
   0.37627462]]
[30.695133 -6.18644   5.280887 20.701084]
{} <function simple_start at 0x7f3f10e8da80>
[[-2.9853198e-01 -5.9050316e-01 -1.1477045e+00 ...  2.2862995e+00
   1.0916107e+00 -1.4314936e+00]
 [ 1.4465290e-01  9.7025967e-

Running Tests:  58%|████████████████████████████                    | 14/24 [00:09<00:07,  1.35it/s]

{} <function harder_func at 0x7f3f10e8db20>
[[-0.3808948  -0.78032225 -0.6346028  ...  1.5596708   0.5516384
  -0.07813679]
 [-0.7503067  -1.4254004  -1.7078948  ...  0.35105577 -0.7838049
   1.1848631 ]
 [ 0.8543656   0.7365179   0.16207914 ...  1.4308524   0.04853599
   0.51077515]
 [-0.5692297   0.46814257 -0.858152   ... -0.19647543 -0.953875
  -1.2080128 ]]
[[-2.3449707 ]
 [-0.89372206]
 [13.32686329]
 [ 0.25162491]]
{} <function harder2_func at 0x7f3f10e8dbc0>
[[ 0.7957516  -0.76905596  0.63915974 ... -0.60530746  0.11949987
  -0.8336425 ]
 [-0.5681423  -1.0231922  -0.33534393 ... -1.5817633   2.0277581
   0.8687367 ]
 [-0.6717876   0.54168135  0.9494901  ...  0.60211945 -0.63835114
   0.08178525]
 [ 1.9662715  -1.9825218  -0.15386629 ... -0.41397026  0.22700775
  -0.34698698]]
[[0.22514792]
 [3.03885722]
 [0.08451822]
 [0.04981413]]
{} <function harder2_func at 0x7f3f10e8dbc0>
[[-0.5071675   1.6746668  -0.5963384  ... -1.3665388   1.4139787
   0.20035064]
 [-1.4726517   0.505785

Running Tests:  62%|██████████████████████████████                  | 15/24 [00:10<00:08,  1.02it/s]

{} <function harder2_func at 0x7f3f10e8dbc0>
[[ 0.4297919  -0.73053837 -0.18953575 ...  1.6140391  -0.25525048
  -2.677661  ]
 [ 0.9499074   0.40692812  0.32139838 ...  0.13654917 -0.87214607
  -0.1297961 ]
 [ 0.5069677   0.35529312  1.9290249  ...  0.35971984  0.43678162
  -1.3268391 ]
 [ 0.96095663 -0.6836404   1.7017277  ...  0.15661106  2.1718168
  -0.11817553]]
[[ 2.56205773]
 [ 6.71694851]
 [-1.15140486]
 [-0.47535494]]
{} <function harder2_func at 0x7f3f10e8dbc0>
[[ 1.8122078  -1.2445601  -0.15749365 ... -0.11384068 -0.4875201
   0.18516079]
 [ 0.40672326  0.5369919   0.97133744 ...  2.0198221   0.36319038
   0.42856845]
 [ 0.97389346  1.4372      0.5853581  ... -0.13274291 -0.8466989
   1.4660383 ]
 [-0.07772256 -0.4462749  -0.01836624 ... -0.09720048 -0.3988777
  -0.18586099]]
[[-1.82984960e+00]
 [-2.96628475e-02]
 [ 3.15582695e+01]
 [-4.80664429e+02]]


/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[ 1.1144738   2.1361156  -0.63951784 ... -0.5680081  -1.3876376
  -0.18500099]
 [ 0.6537486   1.6903279   0.5938302  ...  0.25350708  0.5371816
   0.04044743]
 [ 0.7003774   0.04524689 -0.21745043 ...  1.2157751   0.71724737
   0.6515374 ]
 [ 0.26401076  0.18529078 -3.730468   ... -1.3748761  -0.31934056
   0.39430672]]
[[-12.61160088]
 [         nan]
 [ -2.18785297]
 [ -0.47360571]]
{} <function harder3_func at 0x7f3f10e8dda0>
[[-0.47209707  1.5581113  -0.03362931 ... -1.6396549  -0.3356271
  -0.74893194]
 [ 0.19449888  0.93937314 -1.8720523  ...  0.62591755  0.27819735
   0.58197534]
 [ 0.50342655  0.7013512   0.45353433 ... -0.3436941  -0.72576135
  -0.23298907]
 [ 1.5848444  -0.26505506  1.0828385  ... -0.43904743  0.02097607
   0.5863676 ]]
[[-50.75561905]
 [  0.45456079]
 [         nan]
 [         nan]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[ 0.26930892  0.4624055  -0.22129646 ... -0.9808331   0.1266627
   0.17847781]
 [ 0.01319974  0.12893794  0.98529994 ...  0.4953971   0.9664303
   0.00684979]
 [-0.67628217 -1.4456173  -0.01804353 ...  1.0583352  -0.99635816
   0.19699952]
 [ 0.4613914  -0.31699646 -0.59604126 ... -0.04582451  1.244352
   0.57551455]]
[[        nan]
 [-0.95349985]
 [ 2.19619036]
 [-0.29977933]]
{} <function harder3_func at 0x7f3f10e8dda0>
[[-0.18426548  0.30425838 -0.35833538 ... -0.11059852  1.5814152
  -0.5737567 ]
 [ 0.4877031   0.7045213  -0.94039357 ... -1.0228249  -1.3816705
  -0.16643693]
 [ 0.07445356  1.5262764  -0.9076402  ... -0.25773692 -1.2094846
   0.8715618 ]
 [ 0.38768888  0.9494834   0.16780949 ...  0.2802475   0.09838779
  -0.99767214]]
[[-0.27595446]
 [        nan]
 [-3.67386127]
 [        nan]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[ 0.30493796  0.8177986   1.7920215  ... -0.24819715  1.346045
  -1.8663651 ]
 [ 0.50106543  0.7556017   1.2069997  ... -0.6252825   0.37532243
   0.0660887 ]
 [ 0.47233623 -2.4363468  -0.41628787 ... -1.3700625   1.3040558
  -1.532019  ]
 [-2.6596808  -2.174226    1.8960853  ... -1.7110459  -1.1930165
   0.5006029 ]]
[[        nan]
 [        nan]
 [-2.74170685]
 [ 0.98723698]]
{} <function harder3_func at 0x7f3f10e8dda0>
[[ 0.0503816  -1.3602105   1.381163   ... -1.0532844   2.0666451
  -0.37756613]
 [-1.3661709   0.26370177  2.3756473  ...  1.7272301   0.46022066
   0.9999912 ]
 [ 0.7830341  -0.52271     0.6375294  ...  0.6908014   0.03043527
   0.15556863]
 [-1.3834782   1.7546386  -0.31241202 ...  0.07311299  0.7312378
  -0.03925955]]
[[ 1.02211416]
 [-2.90843911]
 [        nan]
 [        nan]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[ 1.5286618   1.841622   -0.61195314 ...  1.2586838   0.42271066
  -1.1682801 ]
 [-0.87472534 -0.9958445  -0.25121653 ...  0.37178698  0.786823
   0.6346689 ]
 [ 0.24465396  1.5387679   0.10963399 ...  0.38920704  0.800624
   1.1907821 ]
 [-0.5427006  -0.30248225  0.2040864  ...  0.9158228   0.58015656
   0.18414505]]
[[ 0.86032379]
 [ 1.59716189]
 [24.89619827]
 [ 0.5058825 ]]
{} <function harder3_func at 0x7f3f10e8dda0>
[[ 1.7792675  -1.2499528   0.17448768 ... -1.5337002  -0.06469933
   2.850478  ]
 [ 0.7044648  -0.47995478 -0.04746079 ...  1.2427344  -1.3418329
  -0.25194073]
 [ 0.36162588  1.6631665  -0.28731248 ... -0.2809692  -0.61054856
  -0.53568673]
 [ 1.2068874  -1.1278803   1.4124764  ... -0.9753823   1.7461236
  -1.3140181 ]]
[[ -0.77889365]
 [ -0.6383009 ]
 [-12.3698597 ]
 [  5.48609114]]


/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[ 0.4896155  -0.1993752   0.07154482 ... -0.14459409  0.83080155
   1.9617169 ]
 [ 1.4837692   0.9935642  -1.1328355  ... -1.1909808  -0.5661448
   0.5589203 ]
 [-0.7183541   0.7521618   0.20178583 ...  1.1820973  -0.861818
   0.29297915]
 [-0.10513689 -0.3996174   3.254154   ... -0.19164887  0.3255674
  -1.4095917 ]]
[[-4.71638774]
 [ 0.37971503]
 [-0.79412091]
 [-3.07356529]]
{} <function harder3_func at 0x7f3f10e8dda0>
[[ 0.73359233  1.2243555   0.03418773 ... -1.299321   -0.0246517
  -1.3603268 ]
 [ 0.48766306  0.53362083 -0.76006776 ... -0.72970825  0.08258742
  -0.24383228]
 [-1.7534631   0.42674583 -0.49800175 ...  1.6420935  -0.02988906
  -1.0998219 ]
 [-0.18751349 -1.0638065   0.17527856 ...  0.22394751  1.1812141
   1.7313343 ]]
[[69.42002869]
 [ 0.42767304]
 [-0.11857569]
 [ 2.93227625]]


/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[-0.80394804 -1.726921   -0.96169156 ...  0.294316   -0.7632774
  -0.31174052]
 [ 0.10553549  0.22647315 -0.9780156  ... -0.17990494  0.17863214
   0.3855923 ]
 [ 0.64965457 -0.09273792  0.50717634 ...  1.3563186  -1.0630776
   1.1902065 ]
 [-1.1012391  -0.0814438   0.518429   ... -0.27521303 -0.5257516
  -0.35652435]]
[[-10.94765091]
 [ -1.92114845]
 [ -0.6508919 ]
 [  1.11053033]]
{} <function harder3_func at 0x7f3f10e8dda0>
[[-0.9703258   1.5762533   1.8147181  ... -1.4043897  -0.9934463
  -0.7838157 ]
 [-0.78628856  0.4177779   0.21854295 ...  0.8574252   0.7434811
   1.1656039 ]
 [ 1.2241167   1.2106956   0.73417175 ... -1.4055192  -1.0425892
  -0.22495554]
 [-0.48717636  0.53693163  0.22237918 ...  0.44425577 -0.54893297
   0.04427069]]
[[-2.25873899]
 [ 1.56368326]
 [ 4.50510454]
 [-0.58942205]]


/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[ 0.26517257 -0.56668556  0.31314173 ...  0.25870442 -0.7148332
   0.2308188 ]
 [-0.06967726 -0.34853396  1.0759557  ... -0.18870929  1.1312461
  -0.841398  ]
 [-0.10017277  1.0647284  -0.6917464  ...  0.03804201  3.211572
  -0.02759571]
 [-1.8272436   0.12387452 -0.6521942  ... -0.7509584  -0.19676593
   0.94494575]]
[[        nan]
 [ 1.22119918]
 [-2.07620692]
 [        nan]]
{} <function harder3_func at 0x7f3f10e8dda0>
[[-2.631762    1.2065938  -0.12556472 ...  0.26545733  0.23922239
  -1.5209576 ]
 [-0.18860306 -1.1965344   0.5332275  ... -1.0707432  -1.1205919
   0.10374688]
 [-0.26307574 -0.18825628 -0.6157141  ...  0.78660524 -0.1952084
  -0.5383749 ]
 [-3.0779855   0.14271721 -1.0721922  ...  0.75786954  1.0165205
  -0.6810131 ]]
[[        nan]
 [ 1.65763891]
 [-0.53385085]
 [-7.08702723]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
<ast>:2: RuntimeWarning: invalid value encountered in scalar power
Running Tests:  67%|████████████████████████████████                | 16/24 [00:12<00:09,  1.24s/it]

{} <function harder3_func at 0x7f3f10e8dda0>
[[-0.45070323 -0.45477566 -0.6932191  ...  0.5442563   1.3114704
   1.6862822 ]
 [-0.12988599 -0.20578353  1.4065026  ... -0.06687316 -1.447249
  -1.0899119 ]
 [-0.29196084  0.6386615  -1.7783978  ...  0.15433165 -0.25081518
   1.3435668 ]
 [ 0.511097    0.06265531 -0.50847363 ...  0.19987926 -0.25349602
  -0.7267171 ]]
[[        nan]
 [-1.18330688]
 [ 0.42965934]
 [        nan]]
{} <function simple_start at 0x7f3f10e8da80>
[[-0.47661576 -1.43383     0.29942068 ... -0.5229889  -0.89960015
  -0.85218465]
 [-1.6249934  -0.83673966 -0.9584112  ... -0.14757429 -0.6254561
  -0.19722769]
 [-0.7885277  -0.01745891  2.5475228  ... -0.11953409  0.39866847
   0.54348516]
 [ 0.48092172 -1.096718   -0.992776   ... -1.5184815   1.6892698
  -1.7571398 ]]
[ 3.812581   -2.5007205  15.908863    0.10351674]
{} <function simple_start at 0x7f3f10e8da80>
[[ 0.24577013 -0.5925141  -0.8608596  ... -0.50724983 -1.2406735
   0.67645866]
 [ 0.2712346  -1.0076303   0.

Running Tests:  71%|██████████████████████████████████              | 17/24 [00:26<00:33,  4.74s/it]

{} <function simple_start at 0x7f3f10e8da80>
[[ 0.3226836  -0.40715966 -0.0631661  ...  0.22700432  0.9390317
  -0.1969454 ]
 [ 0.45850542  1.0940465   0.14023739 ...  0.05006671  0.89028776
   1.9999515 ]
 [-0.21176451  0.7527243   0.6228016  ...  0.9570814   0.53307664
   0.9482332 ]
 [-0.7219958   0.4566937  -0.4156802  ...  0.7430745  -0.20906758
  -0.12890173]]
[-2.6703317 10.730213   2.2463665  2.2701395]
{} <function harder_func at 0x7f3f10e8db20>
[[-0.19250126 -0.33271784  1.3971728  ...  0.8190975  -1.2200074
  -2.2229648 ]
 [-1.2536485  -0.8776251   0.27224022 ... -0.6780843  -0.49169904
   0.6078463 ]
 [-0.85438675  0.6137953   0.16482815 ... -0.5505081  -0.38173002
   1.3554776 ]
 [-0.78056836  0.79162276  0.2266727  ... -0.43972483  0.46980286
  -0.25530788]]
[[-0.066371  ]
 [ 7.4487133 ]
 [-0.9689554 ]
 [ 0.06160523]]
{} <function harder_func at 0x7f3f10e8db20>
[[-0.99130213  1.7875758  -0.7448048  ...  0.03087591 -0.02234622
  -0.42744333]
 [-0.8441028   1.1601222   0.19

Running Tests:  75%|████████████████████████████████████            | 18/24 [00:41<00:45,  7.60s/it]

{} <function harder_func at 0x7f3f10e8db20>
[[-0.4419108   0.73754764  0.2269218  ... -0.608933   -0.78595537
   1.2064716 ]
 [-1.039709    1.003741   -0.8845069  ... -1.7120659   0.8896945
  -0.7734125 ]
 [-0.7597984  -0.57943606  1.5116034  ... -0.23568271 -0.05279915
   0.5988094 ]
 [-0.45679727 -1.1265934  -1.6299541  ... -0.28698358 -0.540042
  -1.0028425 ]]
[[ 1.76641309]
 [ 0.04051284]
 [ 0.44597644]
 [-0.86227441]]
{} <function harder2_func at 0x7f3f10e8dbc0>
[[ 4.0848136e-01  5.5473471e-01  1.0291756e+00 ...  9.4561642e-01
  -4.0523944e-05 -6.0473287e-01]
 [-1.5403939e+00 -6.8037540e-02  7.9202670e-01 ... -4.8134398e-01
  -2.2106558e-01 -2.4275744e-01]
 [ 1.0318635e+00 -2.8944141e-01  1.3776693e+00 ... -1.4400549e+00
   1.7822272e+00 -5.7986790e-01]
 [ 3.6291793e-01 -5.5413282e-01  7.4423289e-01 ...  3.5231841e-01
   2.8364044e-02  9.0184677e-01]]
[[ 0.25187433]
 [-2.38676596]
 [-0.17855865]
 [-0.54677248]]
{} <function harder2_func at 0x7f3f10e8dbc0>
[[-1.021737   -0.05673083

Running Tests:  79%|██████████████████████████████████████          | 19/24 [00:58<00:51, 10.23s/it]

{} <function harder2_func at 0x7f3f10e8dbc0>
[[-1.2687564  -0.8496619   2.028878   ... -1.0667975   1.5423951
   1.6440725 ]
 [-0.5671125   0.88812333 -1.0436766  ... -0.22025192 -0.15720493
   0.01598201]
 [-0.2159315   1.0073615   0.829526   ...  0.25423706 -0.39382353
  -2.4831936 ]
 [-0.45023817  1.2902387  -0.1499429  ... -1.0406003  -0.59628665
  -0.6046912 ]]
[[-2.59173203]
 [-0.93107688]
 [-0.91259092]
 [18.65542603]]


/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[-0.24908683 -0.9399002   0.25928295 ...  0.6080104   0.6990907
  -0.06731875]
 [ 1.4179869  -2.906785    0.34282285 ...  0.48844573  0.5413499
  -0.2452593 ]
 [-1.2813219  -1.3153819   0.19984604 ... -0.95866936  0.24146475
  -1.617679  ]
 [-0.7998744  -1.2346778  -0.25680542 ...  2.1847315  -0.5211512
  -0.23163244]]
[[ 1.84885144]
 [-2.70357347]
 [ 2.0563821 ]
 [ 2.27351928]]


/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[ 1.6156083  -0.9414721  -0.49642858 ...  0.24946658 -0.7720841
  -1.3759387 ]
 [ 0.34620804  0.4031117   1.7527084  ...  0.15701187  0.39866325
  -2.8332877 ]
 [-1.2101161   1.025921    0.41980347 ...  0.86631143 -0.2320476
  -1.1814662 ]
 [-1.0246006  -2.2364995   1.9751911  ...  0.8147818   0.2124305
  -0.9106284 ]]
[[-0.44576499]
 [ 1.69399894]
 [-2.0800581 ]
 [ 0.69273686]]


/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[ 1.2755262   0.5129042  -0.29496402 ... -0.7752919   0.44195363
   0.12005921]
 [-0.57327867 -0.34033996 -0.7892924  ...  0.5768333   0.0041541
  -0.2792445 ]
 [-0.11887211  1.0457394  -0.9142183  ... -1.0541927  -1.4810548
  -0.7718744 ]
 [ 0.34924743 -2.1341786  -1.0960525  ... -0.1885583   0.05169183
  -0.72587675]]
[[        nan]
 [-1.57554781]
 [-1.85555434]
 [-1.47663367]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[ 0.1881989   2.4037287   0.649772   ...  0.1324161  -0.42757064
  -0.9176489 ]
 [-1.991246    0.9618432  -0.57268625 ... -0.4123927  -0.13531725
  -2.0162866 ]
 [-0.40530273 -0.30699858  0.8883494  ...  0.899599    0.14699657
  -2.5736017 ]
 [ 0.0187646  -0.3026163   0.5974827  ... -1.7872642  -0.10667109
  -0.8653653 ]]
[[9.12685299]
 [0.31035197]
 [       nan]
 [       nan]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[ 0.5661691  -0.8060801   2.3816383  ... -0.44499123 -0.4625741
  -0.94823843]
 [ 1.5620488  -1.8480551   0.5423506  ...  0.7792795   0.3715206
   0.8186966 ]
 [-1.4016683   0.90580046 -0.69150347 ...  1.3874896   0.39577386
  -0.7787309 ]
 [-1.445916   -0.4551129   0.35721833 ...  0.5522735   1.1477356
   0.47905326]]
[[-1.73426986]
 [-1.81235504]
 [ 2.11726145]
 [ 0.61886573]]


/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[-1.1245815  -1.0775608  -0.46888664 ... -0.03820473  0.5699179
  -2.34758   ]
 [ 0.76484174  0.9180669  -0.7683403  ... -1.0661715  -1.1008002
   0.33954635]
 [ 0.8054756  -0.3333616   0.77017856 ...  2.010327   -0.02538468
   0.41757855]
 [-0.36084783 -1.1426073   0.4007276  ... -0.43427682 -0.12069074
   0.15702891]]
[[ 3.46178319]
 [ 0.59879839]
 [-9.44446468]
 [ 1.50032055]]


/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[-0.91058314 -1.1705134  -1.000715   ... -0.59326893  0.67139155
   2.3369062 ]
 [-0.32701427 -1.7792101  -0.5865816  ... -0.03755931  0.03624843
   0.2129327 ]
 [ 1.184359   -1.0566586  -2.0023892  ... -1.3023804   0.4775388
   0.42253688]
 [ 0.67531043 -0.9265799  -0.6721422  ... -0.1917465   2.1018212
  -0.23413728]]
[[-12.98667431]
 [ -6.85452271]
 [ -0.33157897]
 [         nan]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[ 1.4987198   0.4790221   0.5057448  ... -0.27651533 -0.178177
  -0.99219364]
 [-0.7481081   0.3766789   0.6944861  ... -0.1178708  -1.3307847
  -0.5628948 ]
 [-0.22820143 -0.71716607  0.4926272  ... -0.09097279  0.49726003
   1.6075629 ]
 [-0.34644946  0.5343552  -1.1250459  ...  1.6125265   0.36010006
  -1.3589151 ]]
[[        nan]
 [        nan]
 [ 0.65543628]
 [-1.29987736]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[ 0.7758047  -0.607909    0.13068573 ...  0.36086997  1.391776
   1.2133135 ]
 [-0.32036546  0.76878715 -1.8387282  ... -0.5083701   0.7503439
  -0.13156886]
 [ 1.4225066  -0.09203425 -1.2597154  ... -1.7179533   0.48722062
  -0.75742406]
 [-0.6823498   0.6169718   0.03184934 ... -1.0317416   0.15509786
   1.1449076 ]]
[[-3.13465061]
 [-0.70807941]
 [-0.74513016]
 [        nan]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[-2.871186   -0.6911449   1.0969915  ...  0.842347    0.5676509
   0.6204497 ]
 [ 1.5241889  -0.11971743  2.3402781  ...  0.16453983 -0.93013567
  -0.26716658]
 [ 1.1464856   1.1567113   0.75515294 ... -1.3747504  -0.08356424
  -0.5535922 ]
 [-0.6777585   0.7658067  -0.6598104  ...  1.6160643  -0.34284386
   1.3604203 ]]
[[-1.72377849]
 [-0.88793528]
 [        nan]
 [        nan]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[ 0.5654759   2.761416   -0.4603021  ...  0.83032614  1.0569346
   0.40287593]
 [-0.69079816  0.2857838  -1.8139366  ... -0.7017411   1.1029549
  -1.2032691 ]
 [ 0.8164457   0.83414066  2.2051842  ...  0.42738068  0.38487938
   0.7910775 ]
 [-1.2284963  -1.0260339   0.00325835 ... -0.8846547  -0.8746444
   0.66604453]]
[[-20.98426247]
 [         nan]
 [ -0.76438195]
 [  1.7620097 ]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[-0.10537393 -0.84028107  1.961677   ...  0.28866526  0.27531406
   0.26318774]
 [ 0.63413197 -0.44377905  0.48439884 ...  1.5525597   0.03815746
  -1.3916022 ]
 [ 0.01974098 -1.4676301   0.14306626 ... -1.3913327   0.48062044
  -0.20062123]
 [-0.7199862  -0.98368     0.31469843 ...  1.2920723  -1.4756688
  -1.0339594 ]]
[[-1.66198123]
 [-2.96380019]
 [11.90048122]
 [ 4.29061174]]


/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[ 1.208578   -1.2771597   0.9300095  ...  0.2072154  -0.02592958
   0.91407275]
 [ 1.7158579  -0.6712897  -0.9620395  ...  0.84453857 -1.7543104
  -1.7213614 ]
 [ 0.25358954  0.12390881 -0.55133903 ... -1.0190427  -0.25741738
   0.43502712]
 [-1.6040833  -1.4710295  -1.085663   ... -0.9668095   0.17337003
  -1.4756125 ]]
[[-4.58472395]
 [        nan]
 [        nan]
 [ 2.83752275]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[-1.1226329   0.9674879  -0.02265177 ... -0.01421634  1.0238657
   0.3247519 ]
 [-1.0593289  -0.60154223 -0.56428146 ... -1.3483326   1.1263822
  -0.74281615]
 [-0.72754216 -1.2815176  -1.1804425  ...  0.40621808 -0.9403339
   0.46870947]
 [-0.8617337  -0.04504682 -0.2754631  ...  0.5576089  -0.91873646
   1.1838893 ]]
[[ 5.52647305]
 [ 6.5935861 ]
 [-2.82958007]
 [ 3.14288   ]]


/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
Running Tests:  83%|████████████████████████████████████████        | 20/24 [01:18<00:52, 13.02s/it]

{} <function harder3_func at 0x7f3f10e8dda0>
[[ 0.7808022  -1.3040497   1.0262654  ... -0.44841853 -1.3054718
   0.19062687]
 [-1.9370933   0.29762265  1.9298477  ... -0.40198317  2.209232
   0.4653151 ]
 [ 0.6688168  -0.12478351  0.48376015 ... -1.7058662   0.4089223
  -1.3482971 ]
 [ 0.12665021  0.69043523 -0.45521325 ...  0.06235253  0.77567726
   0.42466494]]
[[ 5.31260824]
 [-1.96467438]
 [-0.67429894]
 [-1.82116079]]
{} <function simple_start at 0x7f3f10e8da80>
[[-0.06308588 -1.8861116   0.9799363  ...  1.0501901  -0.5053657
   1.0390537 ]
 [-0.4702891  -1.675983    0.9729754  ...  0.24445792  0.9487086
  -1.2334021 ]
 [ 2.04794    -0.10510492 -0.67782456 ... -2.6833868   0.8243222
   1.036582  ]
 [-0.4077357   0.5223532   0.61279976 ...  0.06605022  1.5346302
  -0.02210595]]
[ 0.88037926 -0.15795064 27.258823    1.3615358 ]
{} <function simple_start at 0x7f3f10e8da80>
[[ 0.13722856  0.03292017  0.0297532  ... -0.6802644  -0.68656504
  -0.60293233]
 [ 2.1874466   0.191532    1.27

Running Tests:  88%|██████████████████████████████████████████      | 21/24 [03:38<02:31, 50.58s/it]

{} <function simple_start at 0x7f3f10e8da80>
[[ 0.43853557 -0.14649929 -1.8372216  ... -1.6418191   1.3393825
   1.2233516 ]
 [ 0.72874534 -0.830349   -0.01318286 ...  0.91314816  0.1142629
   0.18511692]
 [ 0.05492045  1.1796156  -0.20256156 ... -0.7984863  -0.43020564
   2.071127  ]
 [ 0.509434   -0.32258445  0.90155417 ... -1.4564997  -1.6405241
   0.89658964]]
[ 1.9917654  -8.434479   -5.919935   -0.79744726]
{} <function harder_func at 0x7f3f10e8db20>
[[ 0.66381633 -0.31099182  0.02769072 ... -0.7043035   1.6447487
  -0.39464718]
 [-0.89473593  1.7094572   0.65938294 ... -1.2298299   0.24757889
  -2.395296  ]
 [-0.46589437  0.16845696  1.0058434  ... -1.1249901  -0.08391479
  -0.12275526]
 [-1.0188011   0.8791475  -0.21400289 ...  0.37243453 -1.753416
   0.6528743 ]]
[[-40.97089767]
 [  0.72279161]
 [ -0.06346759]
 [  0.74228489]]
{} <function harder_func at 0x7f3f10e8db20>
[[ 0.8011188   0.09267212 -0.7771787  ...  0.18093687  1.0423692
  -0.44125965]
 [ 1.2941755   0.14149061 -0

Running Tests:  92%|████████████████████████████████████████████    | 22/24 [06:07<02:39, 79.69s/it]

{} <function harder_func at 0x7f3f10e8db20>
[[ 0.928794    0.06675588 -0.6046837  ...  0.31168342  0.45456943
   0.83176064]
 [-1.955054   -0.08482037  0.4172686  ...  2.7054272   1.7537909
  -0.4567944 ]
 [-1.701432    1.4943419   0.56191075 ...  0.8566134   1.8595972
   0.74133044]
 [ 1.43013    -0.84147775 -1.1700933  ...  0.895435   -1.1181109
   0.95866454]]
[[-0.11024343]
 [ 0.40911072]
 [-0.23495576]
 [-0.10931261]]
{} <function harder2_func at 0x7f3f10e8dbc0>
[[ 1.436034   -0.68476355 -0.3939832  ... -1.0539471  -2.4945705
   1.9442194 ]
 [ 0.27793872  0.5052619  -0.05775663 ... -0.04203402 -0.37551385
  -0.9230504 ]
 [ 1.5625519  -0.2765829   1.1153904  ... -2.3073192   1.5142711
   1.4170566 ]
 [-0.56152123 -0.48753107  0.9205038  ...  0.81064504  1.3107809
  -0.1740497 ]]
[[-1.0419898 ]
 [-7.28686476]
 [ 2.57833433]
 [-3.46197796]]
{} <function harder2_func at 0x7f3f10e8dbc0>
[[ 0.76469296 -0.08795205  0.02566882 ... -0.8134579  -0.8765513
   0.6391993 ]
 [ 0.69683397 -0.539

Running Tests:  96%|█████████████████████████████████████████████  | 23/24 [08:56<01:46, 106.02s/it]

{} <function harder2_func at 0x7f3f10e8dbc0>
[[ 4.1785479e-01  1.0045274e+00 -1.6167208e+00 ... -1.3805041e+00
   4.6597704e-01  1.4575337e-01]
 [-7.8689754e-01 -1.1335245e+00  5.8358663e-01 ...  2.4950046e-02
   2.1204089e-01  1.0056512e+00]
 [-1.1112100e+00  1.7032356e+00  1.5972180e+00 ...  6.4642668e-02
   8.1442392e-01  8.5565716e-02]
 [-6.1760284e-04 -2.0010719e+00 -2.5213820e-01 ...  1.6442450e+00
   1.5335658e+00 -7.5204080e-01]]
[[-0.43242171]
 [-4.6634407 ]
 [-0.13685448]
 [34.93991089]]


/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[-0.17990854 -0.29444924  0.4075354  ... -0.2717091   0.20824419
   0.74855095]
 [ 0.65413153  0.38790357 -1.8900439  ...  1.3040165   1.3750341
  -0.2012167 ]
 [-0.6973583  -0.426388    1.371741   ...  0.28929064 -0.4948549
  -0.45189857]
 [-0.30741525  1.7919765  -0.16837795 ... -1.0279055  -0.33355653
  -0.20529647]]
[[  3.91522609]
 [         nan]
 [ -1.71979737]
 [-15.66052914]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[ 0.9911915   0.1642255   0.49501505 ...  2.7213442   0.5496006
   0.44220763]
 [ 0.10033763 -0.2746513   2.1754234  ...  0.94545114 -1.1829927
  -0.4110268 ]
 [ 0.6734445   2.3225253   0.03511217 ...  0.03645647 -0.06476579
  -2.9333944 ]
 [ 1.2933673  -0.17616676 -1.4127614  ... -0.71974987 -0.6547539
   0.8856681 ]]
[[         nan]
 [         nan]
 [197.53271484]
 [         nan]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[-1.0812036   0.6986023  -0.08155791 ...  0.4924483   0.42469564
   1.2760872 ]
 [-0.92820513  0.87720066  1.1654221  ...  1.2077117   1.1027875
  -0.16071154]
 [-0.9915022   0.37030664  1.1165761  ...  0.08410211 -0.4913537
   0.2631141 ]
 [ 1.0893785  -0.98627657  0.35735953 ... -0.46150267 -0.6655784
   2.465102  ]]
[[ 2.07636619]
 [-2.00474115]
 [-2.31409454]
 [-1.34733748]]


/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[ 0.71315455  1.7357539  -0.85556334 ...  0.5461542  -0.8403501
  -1.7336842 ]
 [ 0.5120195  -1.0325363  -0.01494361 ... -1.0587655   1.9491383
   1.9770837 ]
 [-0.6827142  -1.1828079   0.9009837  ...  1.681436    1.2963048
  -0.35703668]
 [-0.7048688  -0.74534166  0.46968773 ...  0.9010747   1.7681627
   0.11250282]]
[[        nan]
 [-1.959409  ]
 [ 0.86535227]
 [ 1.12676454]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[ 1.5170822   0.7540165   0.8350956  ...  0.16573684 -0.6184438
   0.204299  ]
 [ 1.1496158  -0.83542067  0.7723591  ... -1.3630874   0.23134443
   0.33328977]
 [-0.22088222  0.43198347  2.0367248  ... -0.55565166 -0.7681156
   0.7211675 ]
 [ 0.05368999  1.1816893  -0.09080502 ... -1.7718155  -1.0727819
  -0.37901977]]
[[ 2.73258519]
 [-2.21446204]
 [        nan]
 [        nan]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
/tmp/ipykernel_911727/2896102278.py:25: RuntimeWarning: divide by zero encountered in scalar divide
  return j / k


{} <function harder3_func at 0x7f3f10e8dda0>
[[ 1.3066163  -0.772558   -0.4239699  ... -0.839569   -1.1489906
  -0.3389353 ]
 [ 1.2146587  -0.29533234 -0.01728659 ... -0.30542514  1.2992795
  -1.4588308 ]
 [-0.64338356  0.49324664 -1.3142353  ... -1.5787373  -0.617916
   1.4306054 ]
 [ 0.31808057 -0.9573798  -0.24537964 ...  0.5093683   0.92491704
  -0.59278905]]
[[-0.44641405]
 [-0.23972847]
 [        nan]
 [-1.699108  ]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[-1.3138559  -1.2320001  -0.7669118  ... -0.19148566 -0.47925973
  -0.87785214]
 [ 0.6742674  -0.7929271  -0.28335565 ...  0.8920735   1.4533268
  -0.16160627]
 [-1.554482    0.8706423  -1.0292598  ...  0.41464084  0.44083437
   0.7854827 ]
 [-0.5685051   0.1783165  -1.9128215  ... -0.35600862  0.584021
   1.1960156 ]]
[[ 2.25251555]
 [-2.59507916]
 [ 3.55425394]
 [-1.49144839]]


/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[ 2.160745    0.02655894 -0.22140442 ...  0.37988916  1.2214814
  -1.1034546 ]
 [-0.31975642 -0.4405022   1.3266408  ...  1.240961    2.1482449
  -1.2863449 ]
 [ 0.4903178  -1.6979666  -0.47912347 ... -0.7224034   0.14643843
   0.2668593 ]
 [-0.4013858  -0.09187888 -1.8009291  ... -1.606218    1.3260497
   0.26961258]]
[[ -0.88559788]
 [         nan]
 [-11.64504198]
 [ -1.25203863]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[-0.34186333 -0.6873166  -0.41356066 ...  0.48348412  0.03676198
   0.05085624]
 [-1.2445257   1.4408118  -0.7028319  ... -0.6300555  -2.0862129
  -0.49701586]
 [ 0.9230226   0.3569181   0.16890483 ... -0.34313992  1.3294523
   1.6890776 ]
 [ 1.1083006   0.30403584 -1.6704668  ...  0.14892562 -0.5548168
   0.84696233]]
[[-9.58636284]
 [ 0.1393055 ]
 [        nan]
 [        nan]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[ 0.7379269  -0.40035185  2.2721648  ... -1.0831133  -0.8062716
   0.28748515]
 [-0.6257682   0.5036257   0.07512762 ... -1.0161879   1.1344498
   0.28551748]
 [-1.2245647   0.33731666  0.08857208 ... -0.747221   -0.7633057
  -0.6498401 ]
 [-0.52865833  1.016804   -0.3934305  ...  1.6038215   0.44029242
   0.6047502 ]]
[[ 1.08588397]
 [-1.51969051]
 [ 1.31833163]
 [-1.12636328]]


/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[ 0.3872629  -1.3035995  -1.4391487  ...  1.4066093  -0.9299936
   2.0906918 ]
 [-0.54261154 -0.099259   -1.1743147  ...  0.32271236  0.862562
  -0.71429765]
 [ 0.15630221  0.10206838 -0.8965851  ...  0.79102457  0.49057773
  -0.546041  ]
 [-0.2983699   0.21017464  0.01313111 ...  0.06052541  0.36691308
   0.876198  ]]
[[        nan]
 [-3.03599142]
 [-1.91492595]
 [        nan]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[-0.5443389  -0.87836564  0.04657711 ...  0.51806694  0.6693025
  -1.4688584 ]
 [-0.5805964   1.2367566  -2.1752253  ...  1.062918   -0.06115692
  -0.8286632 ]
 [-0.79962736 -0.71026087 -0.13556154 ...  0.3268236  -0.62267935
   0.08528212]
 [-0.57258296  0.69686365 -0.672538   ...  1.1810124   2.486962
  -0.13168411]]
[[  1.48644757]
 [  0.77557647]
 [  4.60539282]
 [-20.06939194]]


/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[-1.5713836  -0.6813118   0.97502    ...  0.48513436 -1.0885694
   0.17433372]
 [ 0.279833   -0.19947827  0.21197242 ...  0.9357744  -0.40650928
   0.49467677]
 [-0.11614115  0.77621675  0.00758564 ...  1.4228021   1.6287154
  -1.6246045 ]
 [-0.5118474   0.8239253   0.96025455 ...  1.3201145   0.614009
  -1.451601  ]]
[[-0.97229457]
 [        nan]
 [        nan]
 [ 1.01670734]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))


{} <function harder3_func at 0x7f3f10e8dda0>
[[-0.5014229   0.03975749 -0.6894234  ...  0.25471327  1.0349267
   1.0398576 ]
 [-0.10975806  0.58978665 -0.8765681  ...  1.7344114   0.37232557
  -0.0531483 ]
 [-0.2912393  -0.16245995  0.21914306 ...  1.3483715   0.68074596
   1.1081262 ]
 [ 2.021611   -0.6583084  -0.12444302 ... -0.7167852   1.237942
   0.09242729]]
[[-11.68594777]
 [         nan]
 [ -0.17403609]
 [         nan]]


<ast>:2: RuntimeWarning: invalid value encountered in scalar power
/tmp/ipykernel_911727/2896102278.py:22: RuntimeWarning: invalid value encountered in scalar power
  g=lambda a, b: a if abs(a) > abs(b) else - 2 * (b**(-a))
<ast>:2: RuntimeWarning: invalid value encountered in scalar power
Running Tests: 100%|████████████████████████████████████████████████| 24/24 [12:12<00:00, 30.54s/it]

{} <function harder3_func at 0x7f3f10e8dda0>
[[ 0.56289434 -1.9875224   0.24797449 ...  0.28231013  1.4870409
  -0.3001791 ]
 [ 0.9852874  -0.31637758  0.03794917 ...  0.30307725 -0.35820484
  -1.0771637 ]
 [ 1.1189965  -0.33170986  0.86621165 ...  1.4240428  -0.18498625
  -0.18145421]
 [ 0.05468196 -0.05848348 -0.76874167 ...  0.9175182  -2.444442
   0.06508839]]
[[-6.31120062]
 [-0.33396474]
 [        nan]
 [        nan]]


Pandas Time (s)  \
Size: 10^1, Func: simple_start, Test: apply - 0          0.000469   
Size: 10^1, Func: simple_start, Test: apply - 1          0.000398   
Size: 10^1, Func: simple_start, Test: apply - 2          0.000270   
Size: 10^1, Func: simple_start, Test: apply - 3          0.000258   
Size: 10^1, Func: simple_start, Test: apply - 4          0.000264   
...                                                           ...   
Size: 10^6, Func: harder3_func, Test: apply - 10        13.050153   
Size: 10^6, Func: harder3_func, Test: apply - 11        13.306674   
Size: 10^6, Func: harder3_func, Test: apply - 12        13.049457   
Size: 10^6, Func: harder3_func, Test: apply - 13        13.157856   
Size: 10^6, Func: harder3_func, Test: apply - 14        13.196264   

                                                 Pandopt Time (s)  \
Size: 10^1, Func: simple_start, Test: apply - 0              None   
Size: 10^1, Func: simple_start, Test: apply - 1              None   
Size: 10^1, Func: simple_start, Test: apply - 2              None   
Size: 10^1, Func: simple_start, Test: apply - 3              None   
Size: 10^1, Func: simple_start, Test: apply - 4              None   
...                                                           ...   
Size: 10^6, Func: harder3_func, Test: apply - 10             None   
Size: 10^6, Func: harder3_func, Test: apply - 11             None   
Size: 10^6, Func: harder3_func, Test: apply - 12             None   
Size: 10^6, Func: harder3_func, Test: apply - 13             None   
Size: 10^6, Func: harder3_func, Test: apply - 14             None   

                                                  Checksum Pandas  \
Size: 10^1, Func: simple_start, Test: apply - 0     -2.810120e+02   
Size: 10^1, Func: simple_start, Test: apply - 1     -1.176684e+01   
Size: 10^1, Func: simple_start, Test: apply - 2     -1.143776e+01   
Size: 10^1, Func: simple_start, Test: apply - 3     -3.933148e+01   
Size: 10^1, Func: simple_start, Test: apply - 4      3.309672e+01   
...                                                           ...   
Size: 10^6, Func: harder3_func, Test: apply - 10    -1.745620e+06   
Size: 10^6, Func: harder3_func, Test: apply - 11    -2.322734e+05   
Size: 10^6, Func: harder3_func, Test: apply - 12    -2.570317e+06   
Size: 10^6, Func: harder3_func, Test: apply - 13     3.825290e+06   
Size: 10^6, Func: harder3_func, Test: apply - 14    -7.470579e+05   

                                                 Checksum Pandopt  \
Size: 10^1, Func: simple_start, Test: apply - 0              None   
Size: 10^1, Func: simple_start, Test: apply - 1              None   
Size: 10^1, Func: simple_start, Test: apply - 2              None   
Size: 10^1, Func: simple_start, Test: apply - 3              None   
Size: 10^1, Func: simple_start, Test: apply - 4              None   
...                                                           ...   
Size: 10^6, Func: harder3_func, Test: apply - 10             None   
Size: 10^6, Func: harder3_func, Test: apply - 11             None   
Size: 10^6, Func: harder3_func, Test: apply - 12             None   
Size: 10^6, Func: harder3_func, Test: apply - 13             None   
Size: 10^6, Func: harder3_func, Test: apply - 14             None   

                                                 Pandas Error  \
Size: 10^1, Func: simple_start, Test: apply - 0          None   
Size: 10^1, Func: simple_start, Test: apply - 1          None   
Size: 10^1, Func: simple_start, Test: apply - 2          None   
Size: 10^1, Func: simple_start, Test: apply - 3          None   
Size: 10^1, Func: simple_start, Test: apply - 4          None   
...                                                       ...   
Size: 10^6, Func: harder3_func, Test: apply - 10         None   
Size: 10^6, Func: harder3_func, Test: apply - 11         None   
Size: 10^6, Func: harder3_func, Test: apply - 12         None   
Size: 10^6, Func: harder3_func, Test: apply - 13         None   
Size: 10^6, Func: h

In [4]:
results_df['time reduction'] = results_df["Pandopt Time (s)"] / results_df["Pandas Time (s)"] - 1
results_df['performance multiplicator'] = results_df["Pandas Time (s)"] / results_df["Pandopt Time (s)"] - 1
results_df

Pandas Time (s)  \
Size: 10^1, Func: simple_start, Test: apply - 0          0.000469   
Size: 10^1, Func: simple_start, Test: apply - 1          0.000398   
Size: 10^1, Func: simple_start, Test: apply - 2          0.000270   
Size: 10^1, Func: simple_start, Test: apply - 3          0.000258   
Size: 10^1, Func: simple_start, Test: apply - 4          0.000264   
...                                                           ...   
Size: 10^6, Func: harder3_func, Test: apply - 10        13.050153   
Size: 10^6, Func: harder3_func, Test: apply - 11        13.306674   
Size: 10^6, Func: harder3_func, Test: apply - 12        13.049457   
Size: 10^6, Func: harder3_func, Test: apply - 13        13.157856   
Size: 10^6, Func: harder3_func, Test: apply - 14        13.196264   

                                                 Pandopt Time (s)  \
Size: 10^1, Func: simple_start, Test: apply - 0              None   
Size: 10^1, Func: simple_start, Test: apply - 1              None   
Size: 10^1, Func: simple_start, Test: apply - 2              None   
Size: 10^1, Func: simple_start, Test: apply - 3              None   
Size: 10^1, Func: simple_start, Test: apply - 4              None   
...                                                           ...   
Size: 10^6, Func: harder3_func, Test: apply - 10             None   
Size: 10^6, Func: harder3_func, Test: apply - 11             None   
Size: 10^6, Func: harder3_func, Test: apply - 12             None   
Size: 10^6, Func: harder3_func, Test: apply - 13             None   
Size: 10^6, Func: harder3_func, Test: apply - 14             None   

                                                  Checksum Pandas  \
Size: 10^1, Func: simple_start, Test: apply - 0     -2.810120e+02   
Size: 10^1, Func: simple_start, Test: apply - 1     -1.176684e+01   
Size: 10^1, Func: simple_start, Test: apply - 2     -1.143776e+01   
Size: 10^1, Func: simple_start, Test: apply - 3     -3.933148e+01   
Size: 10^1, Func: simple_start, Test: apply - 4      3.309672e+01   
...                                                           ...   
Size: 10^6, Func: harder3_func, Test: apply - 10    -1.745620e+06   
Size: 10^6, Func: harder3_func, Test: apply - 11    -2.322734e+05   
Size: 10^6, Func: harder3_func, Test: apply - 12    -2.570317e+06   
Size: 10^6, Func: harder3_func, Test: apply - 13     3.825290e+06   
Size: 10^6, Func: harder3_func, Test: apply - 14    -7.470579e+05   

                                                 Checksum Pandopt  \
Size: 10^1, Func: simple_start, Test: apply - 0              None   
Size: 10^1, Func: simple_start, Test: apply - 1              None   
Size: 10^1, Func: simple_start, Test: apply - 2              None   
Size: 10^1, Func: simple_start, Test: apply - 3              None   
Size: 10^1, Func: simple_start, Test: apply - 4              None   
...                                                           ...   
Size: 10^6, Func: harder3_func, Test: apply - 10             None   
Size: 10^6, Func: harder3_func, Test: apply - 11             None   
Size: 10^6, Func: harder3_func, Test: apply - 12             None   
Size: 10^6, Func: harder3_func, Test: apply - 13             None   
Size: 10^6, Func: harder3_func, Test: apply - 14             None   

                                                 Pandas Error  \
Size: 10^1, Func: simple_start, Test: apply - 0          None   
Size: 10^1, Func: simple_start, Test: apply - 1          None   
Size: 10^1, Func: simple_start, Test: apply - 2          None   
Size: 10^1, Func: simple_start, Test: apply - 3          None   
Size: 10^1, Func: simple_start, Test: apply - 4          None   
...                                                       ...   
Size: 10^6, Func: harder3_func, Test: apply - 10         None   
Size: 10^6, Func: harder3_func, Test: apply - 11         None   
Size: 10^6, Func: harder3_func, Test: apply - 12         None   
Size: 10^6, Func: harder3_func, Test: apply - 13         None   
Size: 10^6, Func: h

In [5]:
results_df.to_csv('benchmark.csv')